[package]
name = "kahoot-name"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.11"
# rocket = "0.5.0-rc.2"
rocket_cors = "0.5.2"

# [toolchain]
# channel = "nightly"
